# Use official Node.js image
FROM node:20-alpine

# Set working directory in container
WORKDIR /nuros

# Copy only package.json and package-lock.json for caching dependencies
COPY ./frontend/package*.json ./

# Install dependencies (node_modules will be inside the container)
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose port used by Vite

# Start the Vite development server
CMD ["npm", "run", "dev", "--", "--host"]
