services:

  fastapi:
    image: fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        IS_DEBUG: ${IS_DEBUG:-true}  # Default to 'true' if not set


  celery-worker:
    image: celery-worker:latest
    build:
      context: .
      dockerfile: Dockerfile_celery
    networks:
      - nuros
    env_file:
      - .env
    command: celery -A backend.celery_app.celery_config worker --loglevel=info -Q kick_queue,default
    environment:
      - CELERY_WORKER_CONCURRENCY=4
      - CELERY_WORKER_PREFETCH_MULTIPLIER=1