# This is a complete configuration to deploy Loki locally.
# It uses the modern TSDB store and configures retention via the compactor.
# Includes relevant limits_config for structured metadata and volume features.
# This configuration is suitable for local development or testing environments.
# It is not recommended for production use due to the use of local filesystem storage.

auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  # This is the global retention period applied for all log streams.
  # The compactor will use this value to delete old data.
  # Set to 7 days (168 hours). The minimum retention is 24h.
  retention_period: 168h
  allow_structured_metadata: true
  volume_enabled: true

common:
  # The path_prefix is used by Loki for internal operational files,
  # typically for local temporary data when using an object store.
  path_prefix: /loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  # Filesystem configuration for chunks and index
  filesystem: # Added filesystem configuration
    directory: /loki/chunks # Directory for storing chunks

  # TSDB shipper configuration for the index.
  tsdb_shipper:
    active_index_directory: /loki/active_index_data # Local temporary for active writes
    cache_location: /loki/index_cache # Local directory for index cache

ingester:
  chunk_target_size: 1536 # Value in KB.

compactor:
  working_directory: /loki/compactor_work # Must be writable by Loki user in container
  compaction_interval: 10m
  retention_enabled: true
  delete_request_store: filesystem
  retention_delete_delay: 2h
  retention_delete_worker_count: 50

# Pattern ingester is optional, you can leave it if you find it useful for unstructured logs.
pattern_ingester:
  enabled: true
