apiVersion: 1

templates:
  - orgId: 1
    name: nuspace
    template: |
      {{ define "nuspace.telegram.message" -}}
      {{- if eq .Status "firing" -}}
      🔴 <b>FastAPI недоступен</b>
      {{- else -}}
      ✅ <b>FastAPI восстановлен</b>
      {{- with (index .Alerts 0) }}
      {{- $downtime := .EndsAt.Sub .StartsAt }}
      Даунтайм: <code>{{ printf "%.0f" $downtime.Seconds }}</code> с ({{ $downtime }})
      {{- end }}
      {{- end }}

      {{- with (index .Alerts 0) }}
      <a href="{{ .GeneratorURL }}">Открыть в Grafana</a> · <a href="{{ .SilenceURL }}">Заглушить</a>
      {{- end }}
      {{- end }}
