global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '<bot token>'
        chat_id: <chat id>
        message: |
          [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
