- name: Deploy Docker Containers
  hosts: server
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Pull Docker images
      community.docker.docker_compose_v2:
        project_src: /opt/nuspace
        files:
          - docker-compose.prod.yml
        pull: true
      register: pull_result

    - name: Start Docker containers
      community.docker.docker_compose_v2:
        project_src: /opt/nuspace
        files:
          - docker-compose.prod.yml
        state: present

    - name: Prune unused images
      command: docker system prune -f
      when: pull_result.changed
