---
- name: Deploy Docker Containers
  hosts: webservers
  become: true
  vars:
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    docker_image_tag: "{{ lookup('env', 'DOCKER_IMAGE_TAG') }}"

  tasks:
    - name: Pull latest changes from origin/main
      git:
        repo: "https://github.com/ulanpy/nuspace.git"
        dest: /opt/nuspace
        version: main
        force: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Check if user sa_107337867689943056764 has sudo privileges
      command: sudo -l -U sa_107337867689943056764
      register: sudo_check
      failed_when: false
      changed_when: false

    - name: Ensure user sa_107337867689943056764 is in docker group
      user:
        name: sa_107337867689943056764
        groups: docker
        append: yes

    - name: Ensure user sa_107337867689943056764 is in devs group
      user:
        name: sa_107337867689943056764
        groups: devs
        append: yes

    - name: Pull new images & recreate services
      community.docker.docker_compose_v2:
        project_src: /opt/nuspace/infra
        files:
          - prod.docker-compose.yml
        pull: always
        recreate: always
        state: present
      environment:
        DOCKER_IMAGE_TAG: "{{ docker_image_tag }}"

    - name: Prune all unused Docker images
      command: docker system prune -a -f

    - name: Ensure DOCKER_IMAGE_TAG is set correctly in .bashrc
      lineinfile:
        path: ~/.bashrc
        regexp: "^export DOCKER_IMAGE_TAG="
        line: "export DOCKER_IMAGE_TAG={{ docker_image_tag }}"
        create: yes
