global:
  scrape_interval: 15s

scrape_configs:
  - job_name: grafana
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana:3000
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "(up)"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "grafana_alert_rules.yml"
