"""added templates

Revision ID: 2585ff06573e
Revises: d0bf926cce2a
Create Date: 2025-10-03 07:21:25.696324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2585ff06573e'
down_revision: Union[str, Sequence[str], None] = 'd0bf926cce2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_sub', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_sub'], ['users.sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_sub', name='uq_course_templates_course_student')
    )
    op.create_index(op.f('ix_course_templates_course_id'), 'course_templates', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_templates_id'), 'course_templates', ['id'], unique=False)
    op.create_index(op.f('ix_course_templates_student_sub'), 'course_templates', ['student_sub'], unique=False)
    op.create_table('template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('total_weight_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['course_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_items_id'), 'template_items', ['id'], unique=False)
    op.create_index(op.f('ix_template_items_template_id'), 'template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_items_template_id'), table_name='template_items')
    op.drop_index(op.f('ix_template_items_id'), table_name='template_items')
    op.drop_table('template_items')
    op.drop_index(op.f('ix_course_templates_student_sub'), table_name='course_templates')
    op.drop_index(op.f('ix_course_templates_id'), table_name='course_templates')
    op.drop_index(op.f('ix_course_templates_course_id'), table_name='course_templates')
    op.drop_table('course_templates')
    # ### end Alembic commands ###
