"""added sgotinish

Revision ID: 28748381dea2
Revises: 8299a73354e9
Create Date: 2025-09-23 14:48:11.233738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28748381dea2'
down_revision: Union[str, Sequence[str], None] = '8299a73354e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_sub', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('academic', 'administrative', 'technical', 'complaint', 'suggestion', 'other', name='ticket_category'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', 'resolved', name='ticket_status'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_sub'], ['users.sub'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_author_sub'), 'tickets', ['author_sub'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('sg_member_sub', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='conversation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sg_member_sub'], ['users.sub'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_sg_member_sub'), 'conversations', ['sg_member_sub'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_ticket_id'), 'conversations', ['ticket_id'], unique=False)
    op.create_table('ticket_access',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_sub', sa.String(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'ASSIGN', 'DELEGATE', name='permission_type'), nullable=False),
    sa.Column('granted_by_sub', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_sub'], ['users.sub'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_sub'], ['users.sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_sub', 'permission')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_sub', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_from_sg_member', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_sub'], ['users.sub'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_sub'), 'messages', ['sender_sub'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_table('message_read_status',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_sub', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_sub'], ['users.sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_sub')
    )
    op.create_index(op.f('ix_message_read_status_read_at'), 'message_read_status', ['read_at'], unique=False)
    op.alter_column('communities', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_index(op.f('ix_community_comments_id'), 'community_comments', ['id'], unique=False)
    op.create_index(op.f('ix_community_members_id'), 'community_members', ['id'], unique=False)
    op.create_index(op.f('ix_community_post_tags_id'), 'community_post_tags', ['id'], unique=False)
    op.alter_column('community_posts', 'from_community',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_event_collaborators_id'), 'event_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('grade_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('grade_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('media', 'media_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_media_entity_id'), 'media', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_name'), 'media', ['name'], unique=True)
    op.alter_column('product_reports', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('review_replies', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_review_replies_id'), 'review_replies', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_entity_id'), 'reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.add_column('users', sa.Column('department_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_entity_id'), table_name='reviews')
    op.drop_index(op.f('ix_review_replies_id'), table_name='review_replies')
    op.alter_column('review_replies', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product_reports', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_media_name'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_entity_id'), table_name='media')
    op.alter_column('media', 'media_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('grade_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('grade_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_event_collaborators_id'), table_name='event_collaborators')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.alter_column('community_posts', 'from_community',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_community_post_tags_id'), table_name='community_post_tags')
    op.drop_index(op.f('ix_community_members_id'), table_name='community_members')
    op.drop_index(op.f('ix_community_comments_id'), table_name='community_comments')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.alter_column('communities', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_read_status_read_at'), table_name='message_read_status')
    op.drop_table('message_read_status')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_sub'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('ticket_access')
    op.drop_index(op.f('ix_conversations_ticket_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_sg_member_sub'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_author_sub'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('departments')
    # ### end Alembic commands ###
