"""added student schedule

Revision ID: 5bcd77fc5bda
Revises: 9aafcb4e4c98
Create Date: 2025-10-19 11:42:59.294183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bcd77fc5bda'
down_revision: Union[str, Sequence[str], None] = '9aafcb4e4c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_sub', sa.String(), nullable=False),
    sa.Column('term_label', sa.String(length=64), nullable=True),
    sa.Column('term_value', sa.String(length=32), nullable=True),
    sa.Column('schedule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_sub'], ['users.sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_sub', 'term_value', name='uq_student_schedule_student_term')
    )
    op.create_index(op.f('ix_student_schedules_id'), 'student_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_student_schedules_student_sub'), 'student_schedules', ['student_sub'], unique=False)
    op.create_index(op.f('ix_student_schedules_term_label'), 'student_schedules', ['term_label'], unique=False)
    op.create_index(op.f('ix_student_schedules_term_value'), 'student_schedules', ['term_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_schedules_term_value'), table_name='student_schedules')
    op.drop_index(op.f('ix_student_schedules_term_label'), table_name='student_schedules')
    op.drop_index(op.f('ix_student_schedules_student_sub'), table_name='student_schedules')
    op.drop_index(op.f('ix_student_schedules_id'), table_name='student_schedules')
    op.drop_table('student_schedules')
    # ### end Alembic commands ###
