"""remove unused services

Revision ID: 7ad32f7f934e
Revises: b812fd51979b
Create Date: 2026-07-22 17:01:37.006580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ad32f7f934e'
down_revision: Union[str, Sequence[str], None] = 'b812fd51979b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_members')
    op.drop_index(op.f('ix_community_photo_albums_album_type'), table_name='community_photo_albums')
    op.drop_index(op.f('ix_community_photo_albums_community_id'), table_name='community_photo_albums')
    op.drop_index(op.f('ix_community_photo_albums_created_at'), table_name='community_photo_albums')
    op.drop_table('community_photo_albums')
    op.drop_index(op.f('ix_community_achievements_community_id'), table_name='community_achievements')
    op.drop_index(op.f('ix_community_achievements_year'), table_name='community_achievements')
    op.drop_table('community_achievements')
    op.drop_index(op.f('ix_events_community_id'), table_name='events')
    op.drop_index(op.f('ix_events_scope'), table_name='events')
    op.drop_constraint(op.f('events_community_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'community_id')
    op.drop_column('events', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scope', postgresql.ENUM('personal', 'community', name='event_scope'), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('community_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_community_id_fkey'), 'events', 'communities', ['community_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_events_scope'), 'events', ['scope'], unique=False)
    op.create_index(op.f('ix_events_community_id'), 'events', ['community_id'], unique=False)
    op.create_table('community_achievements',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('community_achievements_community_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('community_achievements_pkey'))
    )
    op.create_index(op.f('ix_community_achievements_year'), 'community_achievements', ['year'], unique=False)
    op.create_index(op.f('ix_community_achievements_community_id'), 'community_achievements', ['community_id'], unique=False)
    op.create_table('community_photo_albums',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('album_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('album_type', postgresql.ENUM('event_photos', 'club_photoshoot', 'other', name='community_photo_album_type'), autoincrement=False, nullable=False),
    sa.Column('album_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('album_thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('album_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('community_photo_albums_community_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('community_photo_albums_pkey'))
    )
    op.create_index(op.f('ix_community_photo_albums_created_at'), 'community_photo_albums', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_photo_albums_community_id'), 'community_photo_albums', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_photo_albums_album_type'), 'community_photo_albums', ['album_type'], unique=False)
    op.create_table('community_members',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_sub', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('community_members_community_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_sub'], ['users.sub'], name=op.f('community_members_user_sub_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('community_members_pkey'))
    )
    # ### end Alembic commands ###
