"""added indexing

Revision ID: 8299a73354e9
Revises: 93a473924e2c
Create Date: 2025-09-16 13:53:59.839209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8299a73354e9'
down_revision: Union[str, Sequence[str], None] = '93a473924e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_communities_category'), 'communities', ['category'], unique=False)
    op.create_index(op.f('ix_communities_created_at'), 'communities', ['created_at'], unique=False)
    op.create_index(op.f('ix_communities_established'), 'communities', ['established'], unique=False)
    op.create_index(op.f('ix_communities_head'), 'communities', ['head'], unique=False)
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=False)
    op.create_index(op.f('ix_communities_recruitment_status'), 'communities', ['recruitment_status'], unique=False)
    op.create_index(op.f('ix_communities_type'), 'communities', ['type'], unique=False)
    op.create_index(op.f('ix_communities_verified'), 'communities', ['verified'], unique=False)
    op.create_index(op.f('ix_community_comments_created_at'), 'community_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_comments_deleted_at'), 'community_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_community_comments_parent_id'), 'community_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_user_sub'), 'community_comments', ['user_sub'], unique=False)
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_tag_id'), 'community_posts', ['tag_id'], unique=False)
    op.create_index(op.f('ix_community_posts_user_sub'), 'community_posts', ['user_sub'], unique=False)
    op.create_index(op.f('ix_event_collaborators_community_id'), 'event_collaborators', ['community_id'], unique=False)
    op.create_index(op.f('ix_event_collaborators_event_id'), 'event_collaborators', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_collaborators_user_sub'), 'event_collaborators', ['user_sub'], unique=False)
    op.create_index(op.f('ix_events_community_id'), 'events', ['community_id'], unique=False)
    op.create_index(op.f('ix_events_creator_sub'), 'events', ['creator_sub'], unique=False)
    op.create_index(op.f('ix_events_end_datetime'), 'events', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_events_policy'), 'events', ['policy'], unique=False)
    op.create_index(op.f('ix_events_scope'), 'events', ['scope'], unique=False)
    op.create_index(op.f('ix_events_start_datetime'), 'events', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_media_entity_type'), 'media', ['entity_type'], unique=False)
    op.create_index(op.f('ix_media_media_format'), 'media', ['media_format'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_media_format'), table_name='media')
    op.drop_index(op.f('ix_media_entity_type'), table_name='media')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_scope'), table_name='events')
    op.drop_index(op.f('ix_events_policy'), table_name='events')
    op.drop_index(op.f('ix_events_end_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_creator_sub'), table_name='events')
    op.drop_index(op.f('ix_events_community_id'), table_name='events')
    op.drop_index(op.f('ix_event_collaborators_user_sub'), table_name='event_collaborators')
    op.drop_index(op.f('ix_event_collaborators_event_id'), table_name='event_collaborators')
    op.drop_index(op.f('ix_event_collaborators_community_id'), table_name='event_collaborators')
    op.drop_index(op.f('ix_community_posts_user_sub'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_tag_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_comments_user_sub'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_parent_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_deleted_at'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_created_at'), table_name='community_comments')
    op.drop_index(op.f('ix_communities_verified'), table_name='communities')
    op.drop_index(op.f('ix_communities_type'), table_name='communities')
    op.drop_index(op.f('ix_communities_recruitment_status'), table_name='communities')
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.drop_index(op.f('ix_communities_head'), table_name='communities')
    op.drop_index(op.f('ix_communities_established'), table_name='communities')
    op.drop_index(op.f('ix_communities_created_at'), table_name='communities')
    op.drop_index(op.f('ix_communities_category'), table_name='communities')
    # ### end Alembic commands ###
