"""adding warpkeys for sgotinish

Revision ID: 9b58a6564166
Revises: e8fc7f0261d4
Create Date: 2026-01-16 23:24:09.015829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b58a6564166'
down_revision: Union[str, Sequence[str], None] = 'e8fc7f0261d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read_status_anon',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_hash', sa.String(length=64), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'owner_hash')
    )
    op.create_index(op.f('ix_message_read_status_anon_read_at'), 'message_read_status_anon', ['read_at'], unique=False)
    op.add_column('tickets', sa.Column('owner_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tickets_owner_hash'), 'tickets', ['owner_hash'], unique=False)
    op.create_unique_constraint(None, 'users', ['sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_tickets_owner_hash'), table_name='tickets')
    op.drop_column('tickets', 'owner_hash')
    op.drop_index(op.f('ix_message_read_status_anon_read_at'), table_name='message_read_status_anon')
    op.drop_table('message_read_status_anon')
    # ### end Alembic commands ###
