"""add_album_metadata_fields

Revision ID: a88f9a3cf2d5
Revises: cb29ee4e7ca3
Create Date: 2026-01-05 14:34:11.106374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88f9a3cf2d5'
down_revision: Union[str, Sequence[str], None] = 'cb29ee4e7ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_photo_albums', sa.Column('album_title', sa.String(), nullable=True))
    op.add_column('community_photo_albums', sa.Column('album_thumbnail_url', sa.String(), nullable=True))
    op.add_column('community_photo_albums', sa.Column('album_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('community_photo_albums', 'album_date')
    op.drop_column('community_photo_albums', 'album_thumbnail_url')
    op.drop_column('community_photo_albums', 'album_title')
    # ### end Alembic commands ###
