"""add community achievements table

Revision ID: a9e8f7d6c5b4
Revises: f57d3dcb5d7b
Create Date: 2025-12-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9e8f7d6c5b4"
# This migration should build on the latest planner/degree-audit changes.
down_revision: Union[str, Sequence[str], None] = "c2f3b1c4a1d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_achievements",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("community_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_achievements_community_id"),
        "community_achievements",
        ["community_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_achievements_year"),
        "community_achievements",
        ["year"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_community_achievements_year"), table_name="community_achievements"
    )
    op.drop_index(
        op.f("ix_community_achievements_community_id"),
        table_name="community_achievements",
    )
    op.drop_table("community_achievements")
    # ### end Alembic commands ###
