"""add community achivements table

Revision ID: a9e8f7d6c5b4
Revises: f57d3dcb5d7b
Create Date: 2025-12-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9e8f7d6c5b4"
down_revision: Union[str, Sequence[str], None] = "f57d3dcb5d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'community_achivements',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('community_id', sa.BigInteger(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_achivements_community_id'), 'community_achivements', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_achivements_year'), 'community_achivements', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_achivements_year'), table_name='community_achivements')
    op.drop_index(op.f('ix_community_achivements_community_id'), table_name='community_achivements')
    op.drop_table('community_achivements')
    # ### end Alembic commands ###
