"""user page owner surrogate id

Adds `users.id`, a sequence-backed surrogate key that user media hangs off.
`users.sub` stays the primary key and every foreign key to it is untouched.
Also adds the 'users' value to the media entity_type enum.

Revision ID: b3c4d5e6f7a8
Revises: a1b2c3d4e5f6
Create Date: 2026-09-29 09:00:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3c4d5e6f7a8"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # GENERATED BY DEFAULT AS IDENTITY is sequence-backed, NOT NULL and backfills
    # existing rows with distinct nextval() results in one statement (PG 10+).
    op.execute("ALTER TABLE users ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY")
    op.create_unique_constraint("uq_users_id", "users", ["id"])

    # Alembic cannot detect enum value changes, so this is manual by design.
    # Guarded because downgrade() cannot remove a PG enum value, so a
    # downgrade/upgrade round trip would otherwise fail on the second upgrade.
    # Safe in-transaction on PG 12+; on older targets wrap the execute in
    # op.get_context().autocommit_block(). The value is not read here.
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_enum e
                JOIN pg_type t ON t.oid = e.enumtypid
                WHERE t.typname = 'entity_type' AND e.enumlabel = 'users'
            ) THEN
                ALTER TYPE entity_type ADD VALUE 'users';
            END IF;
        END $$;
        """)


def downgrade() -> None:
    op.drop_constraint("uq_users_id", "users", type_="unique")
    op.drop_column("users", "id")

    # PG has no "ALTER TYPE ... DROP VALUE", so the 'users' enum value is left
    # in place. It is harmless: nothing reads it once the column is gone.
