"""event suggestion

Revision ID: b812fd51979b
Revises: b2f1c8d4a7e9
Create Date: 2026-07-19 15:26:51.834688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b812fd51979b'
down_revision: Union[str, Sequence[str], None] = 'b2f1c8d4a7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_bot_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('submitter_sub', sa.String(), nullable=False),
    sa.Column('submitter_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending_extract', 'needs_info', 'preview', 'published', 'rejected', 'failed', name='event_bot_submission_status'), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_type', sa.String(), nullable=True),
    sa.Column('origin_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_message_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_date', sa.DateTime(), nullable=True),
    sa.Column('forward_sender_name', sa.String(), nullable=True),
    sa.Column('media_file_unique_id', sa.String(), nullable=True),
    sa.Column('bot_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_caption', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitter_sub'], ['users.sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_bot_submissions_event_id'), 'event_bot_submissions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_bot_submissions_status'), 'event_bot_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_event_bot_submissions_submitter_sub'), 'event_bot_submissions', ['submitter_sub'], unique=False)
    op.create_index(op.f('ix_event_bot_submissions_submitter_telegram_id'), 'event_bot_submissions', ['submitter_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_bot_submissions_submitter_telegram_id'), table_name='event_bot_submissions')
    op.drop_index(op.f('ix_event_bot_submissions_submitter_sub'), table_name='event_bot_submissions')
    op.drop_index(op.f('ix_event_bot_submissions_status'), table_name='event_bot_submissions')
    op.drop_index(op.f('ix_event_bot_submissions_event_id'), table_name='event_bot_submissions')
    op.drop_table('event_bot_submissions')
    # ### end Alembic commands ###
