"""add_community_photo_albums

Revision ID: cb29ee4e7ca3
Revises: d07224c89b5d
Create Date: 2026-01-05 14:10:13.584855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb29ee4e7ca3'
down_revision: Union[str, Sequence[str], None] = 'd07224c89b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_photo_albums',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('album_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('album_type', sa.Enum('event_photos', 'club_photoshoot', 'other', name='community_photo_album_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_photo_albums_album_type'), 'community_photo_albums', ['album_type'], unique=False)
    op.create_index(op.f('ix_community_photo_albums_community_id'), 'community_photo_albums', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_photo_albums_created_at'), 'community_photo_albums', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_photo_albums_created_at'), table_name='community_photo_albums')
    op.drop_index(op.f('ix_community_photo_albums_community_id'), table_name='community_photo_albums')
    op.drop_index(op.f('ix_community_photo_albums_album_type'), table_name='community_photo_albums')
    op.drop_table('community_photo_albums')
    # ### end Alembic commands ###
