"""added_opp_table

Revision ID: d07224c89b5d
Revises: a9e8f7d6c5b4
Create Date: 2026-01-01 15:32:13.031490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd07224c89b5d'
down_revision: Union[str, Sequence[str], None] = 'a9e8f7d6c5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('host', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('RESEARCH', 'INTERNSHIP', 'SUMMER_SCHOOL', 'FORUM', 'SUMMIT', 'GRANT', 'SCHOLARSHIP', 'CONFERENCE', name='opportunity_type'), nullable=False),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('funding', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_eligibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.Enum('UG', 'GRM', 'PHD', name='education_level'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_majors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.Enum('ENGINEERING_MANAGEMENT', 'MECHANICAL_AND_AEROSPACE_ENGINEERING', 'ELECTRICAL_AND_COMPUTER_ENGINEERING', 'CHEMICAL_AND_MATERIALS_ENGINEERING', 'CIVIL_AND_ENVIRONMENTAL_ENGINEERING', 'BIOMEDICAL_ENGINEERING', 'MINING_ENGINEERING', 'PETROLEUM_ENGINEERING', 'ROBOTICS_AND_MECHATRONICS_ENGINEERING', 'COMPUTER_SCIENCE', 'DATA_SCIENCE', 'APPLIED_MATHEMATICS', 'MATHEMATICS', 'ECONOMICS', 'BUSINESS_ADMINISTRATION', 'FINANCE', 'LIFE_SCIENCES', 'BIOLOGICAL_SCIENCES', 'MEDICAL_SCIENCES', 'MOLECULAR_MEDICINE', 'PHARMACOLOGY_AND_TOXICOLOGY', 'PUBLIC_HEALTH', 'SPORTS_MEDICINE_AND_REHABILITATION', 'NURSING', 'DOCTOR_OF_MEDICINE', 'SIX_YEAR_MEDICAL_PROGRAM', 'CHEMISTRY', 'PHYSICS', 'GEOSCIENCES', 'GEOLOGY', 'POLITICAL_SCIENCE_AND_INTERNATIONAL_RELATIONS', 'PUBLIC_POLICY', 'PUBLIC_ADMINISTRATION', 'EURASIAN_STUDIES', 'SOCIOLOGY', 'ANTHROPOLOGY', 'HISTORY', 'EDUCATIONAL_LEADERSHIP', 'MULTILINGUAL_EDUCATION', 'WORLD_LANGUAGES_LITERATURE_AND_CULTURE', name='opportunity_major'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_index(op.f('ix_community_members_id'), table_name='community_members')
    op.drop_index(op.f('ix_course_items_id'), table_name='course_items')
    op.drop_index(op.f('ix_course_templates_id'), table_name='course_templates')
    op.drop_index(op.f('ix_degree_audit_results_id'), table_name='degree_audit_results')
    op.drop_index(op.f('ix_event_collaborators_id'), table_name='event_collaborators')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.alter_column('planner_schedule_courses', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_planner_schedule_courses_schedule'), table_name='planner_schedule_courses')
    op.create_index(op.f('ix_planner_schedule_courses_course_code'), 'planner_schedule_courses', ['course_code'], unique=False)
    op.create_index(op.f('ix_planner_schedule_courses_level'), 'planner_schedule_courses', ['level'], unique=False)
    op.create_index(op.f('ix_planner_schedule_courses_planner_schedule_id'), 'planner_schedule_courses', ['planner_schedule_id'], unique=False)
    op.create_index(op.f('ix_planner_schedule_courses_school'), 'planner_schedule_courses', ['school'], unique=False)
    op.alter_column('planner_schedule_sections', 'is_selected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_planner_schedule_sections_course'), table_name='planner_schedule_sections')
    op.create_index(op.f('ix_planner_schedule_sections_planner_schedule_course_id'), 'planner_schedule_sections', ['planner_schedule_course_id'], unique=False)
    op.drop_index(op.f('ix_student_courses_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_schedules_id'), table_name='student_schedules')
    op.drop_index(op.f('ix_template_items_id'), table_name='template_items')
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.create_unique_constraint(None, 'users', ['sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    op.create_index(op.f('ix_template_items_id'), 'template_items', ['id'], unique=False)
    op.create_index(op.f('ix_student_schedules_id'), 'student_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_student_courses_id'), 'student_courses', ['id'], unique=False)
    op.drop_index(op.f('ix_planner_schedule_sections_planner_schedule_course_id'), table_name='planner_schedule_sections')
    op.create_index(op.f('ix_planner_schedule_sections_course'), 'planner_schedule_sections', ['planner_schedule_course_id'], unique=False)
    op.alter_column('planner_schedule_sections', 'is_selected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_planner_schedule_courses_school'), table_name='planner_schedule_courses')
    op.drop_index(op.f('ix_planner_schedule_courses_planner_schedule_id'), table_name='planner_schedule_courses')
    op.drop_index(op.f('ix_planner_schedule_courses_level'), table_name='planner_schedule_courses')
    op.drop_index(op.f('ix_planner_schedule_courses_course_code'), table_name='planner_schedule_courses')
    op.create_index(op.f('ix_planner_schedule_courses_schedule'), 'planner_schedule_courses', ['planner_schedule_id'], unique=False)
    op.alter_column('planner_schedule_courses', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_event_collaborators_id'), 'event_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_degree_audit_results_id'), 'degree_audit_results', ['id'], unique=False)
    op.create_index(op.f('ix_course_templates_id'), 'course_templates', ['id'], unique=False)
    op.create_index(op.f('ix_course_items_id'), 'course_items', ['id'], unique=False)
    op.create_index(op.f('ix_community_members_id'), 'community_members', ['id'], unique=False)
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.drop_table('opportunity_majors')
    op.drop_table('opportunity_eligibility')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
