"""added entity_type tickets

Revision ID: d0bf926cce2a
Revises: 28748381dea2
Create Date: 2025-09-24 15:36:55.626905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bf926cce2a'
down_revision: Union[str, Sequence[str], None] = '28748381dea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'tickets' to entity_type enum
    op.execute("ALTER TYPE entity_type ADD VALUE 'tickets'")
    
    # Add new user roles to userrole enum
    op.execute("ALTER TYPE userrole ADD VALUE 'boss'")
    op.execute("ALTER TYPE userrole ADD VALUE 'capo'")
    op.execute("ALTER TYPE userrole ADD VALUE 'soldier'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support removing enum values directly.
    # To remove enum values, you would need to:
    # 1. Create a new enum type without the values
    # 2. Update all columns to use the new enum type
    # 3. Drop the old enum type
    # This is a complex operation and should be done manually if needed.
    pass
    # ### end Alembic commands ###
