"""adding CPS school

Revision ID: df3b09aac8a7
Revises: ff17af4961b9
Create Date: 2025-10-12 16:27:18.948648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3b09aac8a7'
down_revision: Union[str, Sequence[str], None] = 'ff17af4961b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE school_type ADD VALUE 'CPS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
