"""full_anon_rej_board

Revision ID: ec352e8c5988
Revises: 9b58a6564166
Create Date: 2026-01-21 14:26:33.962808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec352e8c5988'
down_revision: Union[str, Sequence[str], None] = '9b58a6564166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rejection_board', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rejection_board', sa.Column('nickname', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
