"""remove recruitment column from communities

Revision ID: f64577f64468
Revises: 7ad32f7f934e
Create Date: 2026-07-22 17:21:40.383162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f64577f64468'
down_revision: Union[str, Sequence[str], None] = '7ad32f7f934e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communities_recruitment_status'), table_name='communities')
    op.drop_column('communities', 'recruitment_status')
    op.drop_column('communities', 'recruitment_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('recruitment_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('communities', sa.Column('recruitment_status', postgresql.ENUM('open', 'closed', 'upcoming', name='community_recruitment_status'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_communities_recruitment_status'), 'communities', ['recruitment_status'], unique=False)
    # ### end Alembic commands ###
