"""obtained/max course scores

Revision ID: ff17af4961b9
Revises: 2585ff06573e
Create Date: 2025-10-05 20:14:50.346152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff17af4961b9'
down_revision: Union[str, Sequence[str], None] = '2585ff06573e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    max_score_col = sa.Column('max_score', sa.Numeric(precision=7, scale=2), nullable=True)
    obtained_score_col = sa.Column('obtained_score', sa.Numeric(precision=7, scale=2), nullable=True)
    op.add_column('course_items', max_score_col)
    op.add_column('course_items', obtained_score_col)
    # Populate new columns from the existing percentage-based score.
    op.execute(
        sa.text(
            """
            UPDATE course_items
            SET
                max_score = CASE
                    WHEN obtained_score_pct IS NOT NULL THEN 100
                    ELSE NULL
                END,
                obtained_score = obtained_score_pct
            """
        )
    )
    op.drop_column('course_items', 'obtained_score_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_items', sa.Column('obtained_score_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE course_items
            SET obtained_score_pct =
                CASE
                    WHEN max_score IS NOT NULL AND max_score <> 0
                        THEN (obtained_score / max_score) * 100
                    ELSE obtained_score
                END
            """
        )
    )
    op.drop_column('course_items', 'obtained_score')
    op.drop_column('course_items', 'max_score')
    # ### end Alembic commands ###
