/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppCoursesRouteRouteImport } from './routes/_app/courses/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppAnnouncementsIndexRouteImport } from './routes/_app/announcements/index'
import { Route as AppCommunitiesIndexRouteImport } from './routes/_app/communities/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppDegreeAuditInfoIndexRouteImport } from './routes/_app/degree-audit-info/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppMynuspaceIndexRouteImport } from './routes/_app/mynuspace/index'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/_app/opportunities/index'
import { Route as AppSgotinishIndexRouteImport } from './routes/_app/sgotinish/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as PublicPrivacyPolicyIndexRouteImport } from './routes/_public/privacy-policy/index'
import { Route as PublicTermsOfServiceIndexRouteImport } from './routes/_public/terms-of-service/index'
import { Route as AppCommunitiesSlugIndexRouteImport } from './routes/_app/communities/$slug/index'
import { Route as AppCommunitiesSlugSettingsRouteRouteImport } from './routes/_app/communities/$slug/settings/route'
import { Route as AppCoursesAuditIndexRouteImport } from './routes/_app/courses/audit/index'
import { Route as AppCoursesScheduleIndexRouteImport } from './routes/_app/courses/schedule/index'
import { Route as AppCoursesStatisticsIndexRouteImport } from './routes/_app/courses/statistics/index'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app/events/$eventId/index'
import { Route as AppUSlugIndexRouteImport } from './routes/_app/u/$slug/index'
import { Route as AppUSlugSettingsRouteRouteImport } from './routes/_app/u/$slug/settings/route'
import { Route as AppCommunitiesSlugEditorIndexRouteImport } from './routes/_app/communities/$slug/editor/index'
import { Route as AppCommunitiesSlugSettingsIndexRouteImport } from './routes/_app/communities/$slug/settings/index'
import { Route as AppUSlugEditorIndexRouteImport } from './routes/_app/u/$slug/editor/index'
import { Route as AppUSlugSettingsIndexRouteImport } from './routes/_app/u/$slug/settings/index'
import { Route as AppCommunitiesSlugSettingsAdminControlsIndexRouteImport } from './routes/_app/communities/$slug/settings/admin-controls/index'
import { Route as AppCommunitiesSlugSettingsGeneralIndexRouteImport } from './routes/_app/communities/$slug/settings/general/index'
import { Route as AppUSlugSettingsCommunitiesIndexRouteImport } from './routes/_app/u/$slug/settings/communities/index'
import { Route as AppUSlugSettingsGeneralIndexRouteImport } from './routes/_app/u/$slug/settings/general/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAnnouncementsIndexRoute = AppAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppDegreeAuditInfoIndexRoute = AppDegreeAuditInfoIndexRouteImport.update({
  id: '/degree-audit-info/',
  path: '/degree-audit-info/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMynuspaceIndexRoute = AppMynuspaceIndexRouteImport.update({
  id: '/mynuspace/',
  path: '/mynuspace/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSgotinishIndexRoute = AppSgotinishIndexRouteImport.update({
  id: '/sgotinish/',
  path: '/sgotinish/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyPolicyIndexRoute =
  PublicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicTermsOfServiceIndexRoute =
  PublicTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AppCommunitiesSlugIndexRoute = AppCommunitiesSlugIndexRouteImport.update({
  id: '/communities/$slug/',
  path: '/communities/$slug/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunitiesSlugSettingsRouteRoute =
  AppCommunitiesSlugSettingsRouteRouteImport.update({
    id: '/communities/$slug/settings',
    path: '/communities/$slug/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCoursesAuditIndexRoute = AppCoursesAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesScheduleIndexRoute = AppCoursesScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesStatisticsIndexRoute =
  AppCoursesStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => AppCoursesRouteRoute,
  } as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUSlugIndexRoute = AppUSlugIndexRouteImport.update({
  id: '/u/$slug/',
  path: '/u/$slug/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUSlugSettingsRouteRoute = AppUSlugSettingsRouteRouteImport.update({
  id: '/u/$slug/settings',
  path: '/u/$slug/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunitiesSlugEditorIndexRoute =
  AppCommunitiesSlugEditorIndexRouteImport.update({
    id: '/communities/$slug/editor/',
    path: '/communities/$slug/editor/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCommunitiesSlugSettingsIndexRoute =
  AppCommunitiesSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCommunitiesSlugSettingsRouteRoute,
  } as any)
const AppUSlugEditorIndexRoute = AppUSlugEditorIndexRouteImport.update({
  id: '/u/$slug/editor/',
  path: '/u/$slug/editor/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUSlugSettingsIndexRoute = AppUSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUSlugSettingsRouteRoute,
} as any)
const AppCommunitiesSlugSettingsAdminControlsIndexRoute =
  AppCommunitiesSlugSettingsAdminControlsIndexRouteImport.update({
    id: '/admin-controls/',
    path: '/admin-controls/',
    getParentRoute: () => AppCommunitiesSlugSettingsRouteRoute,
  } as any)
const AppCommunitiesSlugSettingsGeneralIndexRoute =
  AppCommunitiesSlugSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AppCommunitiesSlugSettingsRouteRoute,
  } as any)
const AppUSlugSettingsCommunitiesIndexRoute =
  AppUSlugSettingsCommunitiesIndexRouteImport.update({
    id: '/communities/',
    path: '/communities/',
    getParentRoute: () => AppUSlugSettingsRouteRoute,
  } as any)
const AppUSlugSettingsGeneralIndexRoute =
  AppUSlugSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AppUSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/courses': typeof AppCoursesRouteRouteWithChildren
  '/announcements/': typeof AppAnnouncementsIndexRoute
  '/communities/': typeof AppCommunitiesIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/degree-audit-info/': typeof AppDegreeAuditInfoIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/mynuspace/': typeof AppMynuspaceIndexRoute
  '/opportunities/': typeof AppOpportunitiesIndexRoute
  '/sgotinish/': typeof AppSgotinishIndexRoute
  '/about/': typeof PublicAboutIndexRoute
  '/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof PublicTermsOfServiceIndexRoute
  '/communities/$slug/settings': typeof AppCommunitiesSlugSettingsRouteRouteWithChildren
  '/u/$slug/settings': typeof AppUSlugSettingsRouteRouteWithChildren
  '/communities/$slug/': typeof AppCommunitiesSlugIndexRoute
  '/courses/audit/': typeof AppCoursesAuditIndexRoute
  '/courses/schedule/': typeof AppCoursesScheduleIndexRoute
  '/courses/statistics/': typeof AppCoursesStatisticsIndexRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/u/$slug/': typeof AppUSlugIndexRoute
  '/communities/$slug/editor/': typeof AppCommunitiesSlugEditorIndexRoute
  '/communities/$slug/settings/': typeof AppCommunitiesSlugSettingsIndexRoute
  '/u/$slug/editor/': typeof AppUSlugEditorIndexRoute
  '/u/$slug/settings/': typeof AppUSlugSettingsIndexRoute
  '/communities/$slug/settings/admin-controls/': typeof AppCommunitiesSlugSettingsAdminControlsIndexRoute
  '/communities/$slug/settings/general/': typeof AppCommunitiesSlugSettingsGeneralIndexRoute
  '/u/$slug/settings/communities/': typeof AppUSlugSettingsCommunitiesIndexRoute
  '/u/$slug/settings/general/': typeof AppUSlugSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/announcements': typeof AppAnnouncementsIndexRoute
  '/communities': typeof AppCommunitiesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/degree-audit-info': typeof AppDegreeAuditInfoIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/mynuspace': typeof AppMynuspaceIndexRoute
  '/opportunities': typeof AppOpportunitiesIndexRoute
  '/sgotinish': typeof AppSgotinishIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute
  '/terms-of-service': typeof PublicTermsOfServiceIndexRoute
  '/communities/$slug': typeof AppCommunitiesSlugIndexRoute
  '/courses/audit': typeof AppCoursesAuditIndexRoute
  '/courses/schedule': typeof AppCoursesScheduleIndexRoute
  '/courses/statistics': typeof AppCoursesStatisticsIndexRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/u/$slug': typeof AppUSlugIndexRoute
  '/communities/$slug/editor': typeof AppCommunitiesSlugEditorIndexRoute
  '/communities/$slug/settings': typeof AppCommunitiesSlugSettingsIndexRoute
  '/u/$slug/editor': typeof AppUSlugEditorIndexRoute
  '/u/$slug/settings': typeof AppUSlugSettingsIndexRoute
  '/communities/$slug/settings/admin-controls': typeof AppCommunitiesSlugSettingsAdminControlsIndexRoute
  '/communities/$slug/settings/general': typeof AppCommunitiesSlugSettingsGeneralIndexRoute
  '/u/$slug/settings/communities': typeof AppUSlugSettingsCommunitiesIndexRoute
  '/u/$slug/settings/general': typeof AppUSlugSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_app/announcements/': typeof AppAnnouncementsIndexRoute
  '/_app/communities/': typeof AppCommunitiesIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/degree-audit-info/': typeof AppDegreeAuditInfoIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/mynuspace/': typeof AppMynuspaceIndexRoute
  '/_app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/_app/sgotinish/': typeof AppSgotinishIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute
  '/_public/terms-of-service/': typeof PublicTermsOfServiceIndexRoute
  '/_app/communities/$slug/settings': typeof AppCommunitiesSlugSettingsRouteRouteWithChildren
  '/_app/u/$slug/settings': typeof AppUSlugSettingsRouteRouteWithChildren
  '/_app/communities/$slug/': typeof AppCommunitiesSlugIndexRoute
  '/_app/courses/audit/': typeof AppCoursesAuditIndexRoute
  '/_app/courses/schedule/': typeof AppCoursesScheduleIndexRoute
  '/_app/courses/statistics/': typeof AppCoursesStatisticsIndexRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/u/$slug/': typeof AppUSlugIndexRoute
  '/_app/communities/$slug/editor/': typeof AppCommunitiesSlugEditorIndexRoute
  '/_app/communities/$slug/settings/': typeof AppCommunitiesSlugSettingsIndexRoute
  '/_app/u/$slug/editor/': typeof AppUSlugEditorIndexRoute
  '/_app/u/$slug/settings/': typeof AppUSlugSettingsIndexRoute
  '/_app/communities/$slug/settings/admin-controls/': typeof AppCommunitiesSlugSettingsAdminControlsIndexRoute
  '/_app/communities/$slug/settings/general/': typeof AppCommunitiesSlugSettingsGeneralIndexRoute
  '/_app/u/$slug/settings/communities/': typeof AppUSlugSettingsCommunitiesIndexRoute
  '/_app/u/$slug/settings/general/': typeof AppUSlugSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/announcements/'
    | '/communities/'
    | '/contacts/'
    | '/courses/'
    | '/degree-audit-info/'
    | '/events/'
    | '/mynuspace/'
    | '/opportunities/'
    | '/sgotinish/'
    | '/about/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/communities/$slug/settings'
    | '/u/$slug/settings'
    | '/communities/$slug/'
    | '/courses/audit/'
    | '/courses/schedule/'
    | '/courses/statistics/'
    | '/events/$eventId/'
    | '/u/$slug/'
    | '/communities/$slug/editor/'
    | '/communities/$slug/settings/'
    | '/u/$slug/editor/'
    | '/u/$slug/settings/'
    | '/communities/$slug/settings/admin-controls/'
    | '/communities/$slug/settings/general/'
    | '/u/$slug/settings/communities/'
    | '/u/$slug/settings/general/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/communities'
    | '/contacts'
    | '/courses'
    | '/degree-audit-info'
    | '/events'
    | '/mynuspace'
    | '/opportunities'
    | '/sgotinish'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/communities/$slug'
    | '/courses/audit'
    | '/courses/schedule'
    | '/courses/statistics'
    | '/events/$eventId'
    | '/u/$slug'
    | '/communities/$slug/editor'
    | '/communities/$slug/settings'
    | '/u/$slug/editor'
    | '/u/$slug/settings'
    | '/communities/$slug/settings/admin-controls'
    | '/communities/$slug/settings/general'
    | '/u/$slug/settings/communities'
    | '/u/$slug/settings/general'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/courses'
    | '/_public/'
    | '/_app/announcements/'
    | '/_app/communities/'
    | '/_app/contacts/'
    | '/_app/courses/'
    | '/_app/degree-audit-info/'
    | '/_app/events/'
    | '/_app/mynuspace/'
    | '/_app/opportunities/'
    | '/_app/sgotinish/'
    | '/_public/about/'
    | '/_public/privacy-policy/'
    | '/_public/terms-of-service/'
    | '/_app/communities/$slug/settings'
    | '/_app/u/$slug/settings'
    | '/_app/communities/$slug/'
    | '/_app/courses/audit/'
    | '/_app/courses/schedule/'
    | '/_app/courses/statistics/'
    | '/_app/events/$eventId/'
    | '/_app/u/$slug/'
    | '/_app/communities/$slug/editor/'
    | '/_app/communities/$slug/settings/'
    | '/_app/u/$slug/editor/'
    | '/_app/u/$slug/settings/'
    | '/_app/communities/$slug/settings/admin-controls/'
    | '/_app/communities/$slug/settings/general/'
    | '/_app/u/$slug/settings/communities/'
    | '/_app/u/$slug/settings/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/announcements/': {
      id: '/_app/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AppAnnouncementsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities/': {
      id: '/_app/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/degree-audit-info/': {
      id: '/_app/degree-audit-info/'
      path: '/degree-audit-info'
      fullPath: '/degree-audit-info/'
      preLoaderRoute: typeof AppDegreeAuditInfoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mynuspace/': {
      id: '/_app/mynuspace/'
      path: '/mynuspace'
      fullPath: '/mynuspace/'
      preLoaderRoute: typeof AppMynuspaceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/opportunities/': {
      id: '/_app/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sgotinish/': {
      id: '/_app/sgotinish/'
      path: '/sgotinish'
      fullPath: '/sgotinish/'
      preLoaderRoute: typeof AppSgotinishIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PublicPrivacyPolicyIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms-of-service/': {
      id: '/_public/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof PublicTermsOfServiceIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/communities/$slug/': {
      id: '/_app/communities/$slug/'
      path: '/communities/$slug'
      fullPath: '/communities/$slug/'
      preLoaderRoute: typeof AppCommunitiesSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities/$slug/settings': {
      id: '/_app/communities/$slug/settings'
      path: '/communities/$slug/settings'
      fullPath: '/communities/$slug/settings'
      preLoaderRoute: typeof AppCommunitiesSlugSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/audit/': {
      id: '/_app/courses/audit/'
      path: '/audit'
      fullPath: '/courses/audit/'
      preLoaderRoute: typeof AppCoursesAuditIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/schedule/': {
      id: '/_app/courses/schedule/'
      path: '/schedule'
      fullPath: '/courses/schedule/'
      preLoaderRoute: typeof AppCoursesScheduleIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/statistics/': {
      id: '/_app/courses/statistics/'
      path: '/statistics'
      fullPath: '/courses/statistics/'
      preLoaderRoute: typeof AppCoursesStatisticsIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/u/$slug/': {
      id: '/_app/u/$slug/'
      path: '/u/$slug'
      fullPath: '/u/$slug/'
      preLoaderRoute: typeof AppUSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/u/$slug/settings': {
      id: '/_app/u/$slug/settings'
      path: '/u/$slug/settings'
      fullPath: '/u/$slug/settings'
      preLoaderRoute: typeof AppUSlugSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities/$slug/editor/': {
      id: '/_app/communities/$slug/editor/'
      path: '/communities/$slug/editor'
      fullPath: '/communities/$slug/editor/'
      preLoaderRoute: typeof AppCommunitiesSlugEditorIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities/$slug/settings/': {
      id: '/_app/communities/$slug/settings/'
      path: '/'
      fullPath: '/communities/$slug/settings/'
      preLoaderRoute: typeof AppCommunitiesSlugSettingsIndexRouteImport
      parentRoute: typeof AppCommunitiesSlugSettingsRouteRoute
    }
    '/_app/u/$slug/editor/': {
      id: '/_app/u/$slug/editor/'
      path: '/u/$slug/editor'
      fullPath: '/u/$slug/editor/'
      preLoaderRoute: typeof AppUSlugEditorIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/u/$slug/settings/': {
      id: '/_app/u/$slug/settings/'
      path: '/'
      fullPath: '/u/$slug/settings/'
      preLoaderRoute: typeof AppUSlugSettingsIndexRouteImport
      parentRoute: typeof AppUSlugSettingsRouteRoute
    }
    '/_app/communities/$slug/settings/admin-controls/': {
      id: '/_app/communities/$slug/settings/admin-controls/'
      path: '/admin-controls'
      fullPath: '/communities/$slug/settings/admin-controls/'
      preLoaderRoute: typeof AppCommunitiesSlugSettingsAdminControlsIndexRouteImport
      parentRoute: typeof AppCommunitiesSlugSettingsRouteRoute
    }
    '/_app/communities/$slug/settings/general/': {
      id: '/_app/communities/$slug/settings/general/'
      path: '/general'
      fullPath: '/communities/$slug/settings/general/'
      preLoaderRoute: typeof AppCommunitiesSlugSettingsGeneralIndexRouteImport
      parentRoute: typeof AppCommunitiesSlugSettingsRouteRoute
    }
    '/_app/u/$slug/settings/communities/': {
      id: '/_app/u/$slug/settings/communities/'
      path: '/communities'
      fullPath: '/u/$slug/settings/communities/'
      preLoaderRoute: typeof AppUSlugSettingsCommunitiesIndexRouteImport
      parentRoute: typeof AppUSlugSettingsRouteRoute
    }
    '/_app/u/$slug/settings/general/': {
      id: '/_app/u/$slug/settings/general/'
      path: '/general'
      fullPath: '/u/$slug/settings/general/'
      preLoaderRoute: typeof AppUSlugSettingsGeneralIndexRouteImport
      parentRoute: typeof AppUSlugSettingsRouteRoute
    }
  }
}

interface AppCoursesRouteRouteChildren {
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesAuditIndexRoute: typeof AppCoursesAuditIndexRoute
  AppCoursesScheduleIndexRoute: typeof AppCoursesScheduleIndexRoute
  AppCoursesStatisticsIndexRoute: typeof AppCoursesStatisticsIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesAuditIndexRoute: AppCoursesAuditIndexRoute,
  AppCoursesScheduleIndexRoute: AppCoursesScheduleIndexRoute,
  AppCoursesStatisticsIndexRoute: AppCoursesStatisticsIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppCommunitiesSlugSettingsRouteRouteChildren {
  AppCommunitiesSlugSettingsIndexRoute: typeof AppCommunitiesSlugSettingsIndexRoute
  AppCommunitiesSlugSettingsAdminControlsIndexRoute: typeof AppCommunitiesSlugSettingsAdminControlsIndexRoute
  AppCommunitiesSlugSettingsGeneralIndexRoute: typeof AppCommunitiesSlugSettingsGeneralIndexRoute
}

const AppCommunitiesSlugSettingsRouteRouteChildren: AppCommunitiesSlugSettingsRouteRouteChildren =
  {
    AppCommunitiesSlugSettingsIndexRoute: AppCommunitiesSlugSettingsIndexRoute,
    AppCommunitiesSlugSettingsAdminControlsIndexRoute:
      AppCommunitiesSlugSettingsAdminControlsIndexRoute,
    AppCommunitiesSlugSettingsGeneralIndexRoute:
      AppCommunitiesSlugSettingsGeneralIndexRoute,
  }

const AppCommunitiesSlugSettingsRouteRouteWithChildren =
  AppCommunitiesSlugSettingsRouteRoute._addFileChildren(
    AppCommunitiesSlugSettingsRouteRouteChildren,
  )

interface AppUSlugSettingsRouteRouteChildren {
  AppUSlugSettingsIndexRoute: typeof AppUSlugSettingsIndexRoute
  AppUSlugSettingsCommunitiesIndexRoute: typeof AppUSlugSettingsCommunitiesIndexRoute
  AppUSlugSettingsGeneralIndexRoute: typeof AppUSlugSettingsGeneralIndexRoute
}

const AppUSlugSettingsRouteRouteChildren: AppUSlugSettingsRouteRouteChildren = {
  AppUSlugSettingsIndexRoute: AppUSlugSettingsIndexRoute,
  AppUSlugSettingsCommunitiesIndexRoute: AppUSlugSettingsCommunitiesIndexRoute,
  AppUSlugSettingsGeneralIndexRoute: AppUSlugSettingsGeneralIndexRoute,
}

const AppUSlugSettingsRouteRouteWithChildren =
  AppUSlugSettingsRouteRoute._addFileChildren(
    AppUSlugSettingsRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppAnnouncementsIndexRoute: typeof AppAnnouncementsIndexRoute
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDegreeAuditInfoIndexRoute: typeof AppDegreeAuditInfoIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMynuspaceIndexRoute: typeof AppMynuspaceIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
  AppSgotinishIndexRoute: typeof AppSgotinishIndexRoute
  AppCommunitiesSlugSettingsRouteRoute: typeof AppCommunitiesSlugSettingsRouteRouteWithChildren
  AppUSlugSettingsRouteRoute: typeof AppUSlugSettingsRouteRouteWithChildren
  AppCommunitiesSlugIndexRoute: typeof AppCommunitiesSlugIndexRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppUSlugIndexRoute: typeof AppUSlugIndexRoute
  AppCommunitiesSlugEditorIndexRoute: typeof AppCommunitiesSlugEditorIndexRoute
  AppUSlugEditorIndexRoute: typeof AppUSlugEditorIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppAnnouncementsIndexRoute: AppAnnouncementsIndexRoute,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDegreeAuditInfoIndexRoute: AppDegreeAuditInfoIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMynuspaceIndexRoute: AppMynuspaceIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
  AppSgotinishIndexRoute: AppSgotinishIndexRoute,
  AppCommunitiesSlugSettingsRouteRoute:
    AppCommunitiesSlugSettingsRouteRouteWithChildren,
  AppUSlugSettingsRouteRoute: AppUSlugSettingsRouteRouteWithChildren,
  AppCommunitiesSlugIndexRoute: AppCommunitiesSlugIndexRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppUSlugIndexRoute: AppUSlugIndexRoute,
  AppCommunitiesSlugEditorIndexRoute: AppCommunitiesSlugEditorIndexRoute,
  AppUSlugEditorIndexRoute: AppUSlugEditorIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute
  PublicTermsOfServiceIndexRoute: typeof PublicTermsOfServiceIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicTermsOfServiceIndexRoute: PublicTermsOfServiceIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
