/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppAnnouncementsRouteImport } from './routes/_app/announcements'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppCoursesRouteRouteImport } from './routes/_app/courses/route'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSgotinishRouteImport } from './routes/_app/sgotinish'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicTermsOfServiceRouteImport } from './routes/_public/terms-of-service'
import { Route as AppCommunitiesIndexRouteImport } from './routes/_app/communities/index'
import { Route as AppCommunitiesCommunityIdRouteImport } from './routes/_app/communities/$communityId'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCoursesAuditRouteImport } from './routes/_app/courses/audit'
import { Route as AppCoursesScheduleRouteImport } from './routes/_app/courses/schedule'
import { Route as AppCoursesStatisticsRouteImport } from './routes/_app/courses/statistics'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSgotinishRoute = AppSgotinishRouteImport.update({
  id: '/sgotinish',
  path: '/sgotinish',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsOfServiceRoute = PublicTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => PublicRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesCommunityIdRoute =
  AppCommunitiesCommunityIdRouteImport.update({
    id: '/communities/$communityId',
    path: '/communities/$communityId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesAuditRoute = AppCoursesAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesScheduleRoute = AppCoursesScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesStatisticsRoute = AppCoursesStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/courses': typeof AppCoursesRouteRouteWithChildren
  '/announcements': typeof AppAnnouncementsRoute
  '/contacts': typeof AppContactsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/profile': typeof AppProfileRoute
  '/sgotinish': typeof AppSgotinishRoute
  '/about': typeof PublicAboutRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/courses/audit': typeof AppCoursesAuditRoute
  '/courses/schedule': typeof AppCoursesScheduleRoute
  '/courses/statistics': typeof AppCoursesStatisticsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/communities/': typeof AppCommunitiesIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/events/': typeof AppEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/contacts': typeof AppContactsRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/profile': typeof AppProfileRoute
  '/sgotinish': typeof AppSgotinishRoute
  '/about': typeof PublicAboutRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/courses/audit': typeof AppCoursesAuditRoute
  '/courses/schedule': typeof AppCoursesScheduleRoute
  '/courses/statistics': typeof AppCoursesStatisticsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/communities': typeof AppCommunitiesIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/events': typeof AppEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteRouteWithChildren
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sgotinish': typeof AppSgotinishRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/terms-of-service': typeof PublicTermsOfServiceRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/_app/courses/audit': typeof AppCoursesAuditRoute
  '/_app/courses/schedule': typeof AppCoursesScheduleRoute
  '/_app/courses/statistics': typeof AppCoursesStatisticsRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/communities/': typeof AppCommunitiesIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/announcements'
    | '/contacts'
    | '/opportunities'
    | '/profile'
    | '/sgotinish'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/communities/$communityId'
    | '/courses/audit'
    | '/courses/schedule'
    | '/courses/statistics'
    | '/events/$eventId'
    | '/communities/'
    | '/courses/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/contacts'
    | '/opportunities'
    | '/profile'
    | '/sgotinish'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/communities/$communityId'
    | '/courses/audit'
    | '/courses/schedule'
    | '/courses/statistics'
    | '/events/$eventId'
    | '/communities'
    | '/courses'
    | '/events'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/courses'
    | '/_app/announcements'
    | '/_app/contacts'
    | '/_app/opportunities'
    | '/_app/profile'
    | '/_app/sgotinish'
    | '/_public/about'
    | '/_public/privacy-policy'
    | '/_public/terms-of-service'
    | '/_public/'
    | '/_app/communities/$communityId'
    | '/_app/courses/audit'
    | '/_app/courses/schedule'
    | '/_app/courses/statistics'
    | '/_app/events/$eventId'
    | '/_app/communities/'
    | '/_app/courses/'
    | '/_app/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sgotinish': {
      id: '/_app/sgotinish'
      path: '/sgotinish'
      fullPath: '/sgotinish'
      preLoaderRoute: typeof AppSgotinishRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms-of-service': {
      id: '/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PublicTermsOfServiceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/communities/': {
      id: '/_app/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/$communityId': {
      id: '/_app/communities/$communityId'
      path: '/communities/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof AppCommunitiesCommunityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/audit': {
      id: '/_app/courses/audit'
      path: '/audit'
      fullPath: '/courses/audit'
      preLoaderRoute: typeof AppCoursesAuditRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/schedule': {
      id: '/_app/courses/schedule'
      path: '/schedule'
      fullPath: '/courses/schedule'
      preLoaderRoute: typeof AppCoursesScheduleRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/statistics': {
      id: '/_app/courses/statistics'
      path: '/statistics'
      fullPath: '/courses/statistics'
      preLoaderRoute: typeof AppCoursesStatisticsRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCoursesRouteRouteChildren {
  AppCoursesAuditRoute: typeof AppCoursesAuditRoute
  AppCoursesScheduleRoute: typeof AppCoursesScheduleRoute
  AppCoursesStatisticsRoute: typeof AppCoursesStatisticsRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesAuditRoute: AppCoursesAuditRoute,
  AppCoursesScheduleRoute: AppCoursesScheduleRoute,
  AppCoursesStatisticsRoute: AppCoursesStatisticsRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppRouteChildren {
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSgotinishRoute: typeof AppSgotinishRoute
  AppCommunitiesCommunityIdRoute: typeof AppCommunitiesCommunityIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppContactsRoute: AppContactsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSgotinishRoute: AppSgotinishRoute,
  AppCommunitiesCommunityIdRoute: AppCommunitiesCommunityIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTermsOfServiceRoute: typeof PublicTermsOfServiceRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTermsOfServiceRoute: PublicTermsOfServiceRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
