/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppCoursesRouteRouteImport } from './routes/_app/courses/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppAnnouncementsIndexRouteImport } from './routes/_app/announcements/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppDegreeAuditInfoIndexRouteImport } from './routes/_app/degree-audit-info/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppMynuspaceIndexRouteImport } from './routes/_app/mynuspace/index'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/_app/opportunities/index'
import { Route as AppSgotinishIndexRouteImport } from './routes/_app/sgotinish/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as PublicPrivacyPolicyIndexRouteImport } from './routes/_public/privacy-policy/index'
import { Route as PublicTermsOfServiceIndexRouteImport } from './routes/_public/terms-of-service/index'
import { Route as AppCoursesAuditIndexRouteImport } from './routes/_app/courses/audit/index'
import { Route as AppCoursesScheduleIndexRouteImport } from './routes/_app/courses/schedule/index'
import { Route as AppCoursesStatisticsIndexRouteImport } from './routes/_app/courses/statistics/index'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app/events/$eventId/index'
import { Route as AppPSlugIndexRouteImport } from './routes/_app/p/$slug/index'
import { Route as AppPSlugSettingsRouteRouteImport } from './routes/_app/p/$slug/settings/route'
import { Route as AppPSlugEditorIndexRouteImport } from './routes/_app/p/$slug/editor/index'
import { Route as AppPSlugSettingsIndexRouteImport } from './routes/_app/p/$slug/settings/index'
import { Route as AppPSlugSettingsAdminControlsIndexRouteImport } from './routes/_app/p/$slug/settings/admin-controls/index'
import { Route as AppPSlugSettingsGeneralIndexRouteImport } from './routes/_app/p/$slug/settings/general/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnnouncementsIndexRoute = AppAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppDegreeAuditInfoIndexRoute = AppDegreeAuditInfoIndexRouteImport.update({
  id: '/degree-audit-info/',
  path: '/degree-audit-info/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMynuspaceIndexRoute = AppMynuspaceIndexRouteImport.update({
  id: '/mynuspace/',
  path: '/mynuspace/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSgotinishIndexRoute = AppSgotinishIndexRouteImport.update({
  id: '/sgotinish/',
  path: '/sgotinish/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyPolicyIndexRoute =
  PublicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicTermsOfServiceIndexRoute =
  PublicTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AppCoursesAuditIndexRoute = AppCoursesAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesScheduleIndexRoute = AppCoursesScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesStatisticsIndexRoute =
  AppCoursesStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => AppCoursesRouteRoute,
  } as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugIndexRoute = AppPSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugSettingsRouteRoute = AppPSlugSettingsRouteRouteImport.update({
  id: '/p/$slug/settings',
  path: '/p/$slug/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugEditorIndexRoute = AppPSlugEditorIndexRouteImport.update({
  id: '/p/$slug/editor/',
  path: '/p/$slug/editor/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugSettingsIndexRoute = AppPSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPSlugSettingsRouteRoute,
} as any)
const AppPSlugSettingsAdminControlsIndexRoute =
  AppPSlugSettingsAdminControlsIndexRouteImport.update({
    id: '/admin-controls/',
    path: '/admin-controls/',
    getParentRoute: () => AppPSlugSettingsRouteRoute,
  } as any)
const AppPSlugSettingsGeneralIndexRoute =
  AppPSlugSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AppPSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/courses': typeof AppCoursesRouteRouteWithChildren
  '/account/': typeof AppAccountIndexRoute
  '/announcements/': typeof AppAnnouncementsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/degree-audit-info/': typeof AppDegreeAuditInfoIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/mynuspace/': typeof AppMynuspaceIndexRoute
  '/opportunities/': typeof AppOpportunitiesIndexRoute
  '/sgotinish/': typeof AppSgotinishIndexRoute
  '/about/': typeof PublicAboutIndexRoute
  '/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof PublicTermsOfServiceIndexRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRouteRouteWithChildren
  '/courses/audit/': typeof AppCoursesAuditIndexRoute
  '/courses/schedule/': typeof AppCoursesScheduleIndexRoute
  '/courses/statistics/': typeof AppCoursesStatisticsIndexRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/p/$slug/': typeof AppPSlugIndexRoute
  '/p/$slug/editor/': typeof AppPSlugEditorIndexRoute
  '/p/$slug/settings/': typeof AppPSlugSettingsIndexRoute
  '/p/$slug/settings/admin-controls/': typeof AppPSlugSettingsAdminControlsIndexRoute
  '/p/$slug/settings/general/': typeof AppPSlugSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AppAccountIndexRoute
  '/announcements': typeof AppAnnouncementsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/degree-audit-info': typeof AppDegreeAuditInfoIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/mynuspace': typeof AppMynuspaceIndexRoute
  '/opportunities': typeof AppOpportunitiesIndexRoute
  '/sgotinish': typeof AppSgotinishIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute
  '/terms-of-service': typeof PublicTermsOfServiceIndexRoute
  '/courses/audit': typeof AppCoursesAuditIndexRoute
  '/courses/schedule': typeof AppCoursesScheduleIndexRoute
  '/courses/statistics': typeof AppCoursesStatisticsIndexRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/p/$slug': typeof AppPSlugIndexRoute
  '/p/$slug/editor': typeof AppPSlugEditorIndexRoute
  '/p/$slug/settings': typeof AppPSlugSettingsIndexRoute
  '/p/$slug/settings/admin-controls': typeof AppPSlugSettingsAdminControlsIndexRoute
  '/p/$slug/settings/general': typeof AppPSlugSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/announcements/': typeof AppAnnouncementsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/degree-audit-info/': typeof AppDegreeAuditInfoIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/mynuspace/': typeof AppMynuspaceIndexRoute
  '/_app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/_app/sgotinish/': typeof AppSgotinishIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute
  '/_public/terms-of-service/': typeof PublicTermsOfServiceIndexRoute
  '/_app/p/$slug/settings': typeof AppPSlugSettingsRouteRouteWithChildren
  '/_app/courses/audit/': typeof AppCoursesAuditIndexRoute
  '/_app/courses/schedule/': typeof AppCoursesScheduleIndexRoute
  '/_app/courses/statistics/': typeof AppCoursesStatisticsIndexRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/p/$slug/': typeof AppPSlugIndexRoute
  '/_app/p/$slug/editor/': typeof AppPSlugEditorIndexRoute
  '/_app/p/$slug/settings/': typeof AppPSlugSettingsIndexRoute
  '/_app/p/$slug/settings/admin-controls/': typeof AppPSlugSettingsAdminControlsIndexRoute
  '/_app/p/$slug/settings/general/': typeof AppPSlugSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/account/'
    | '/announcements/'
    | '/contacts/'
    | '/courses/'
    | '/degree-audit-info/'
    | '/events/'
    | '/mynuspace/'
    | '/opportunities/'
    | '/sgotinish/'
    | '/about/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/p/$slug/settings'
    | '/courses/audit/'
    | '/courses/schedule/'
    | '/courses/statistics/'
    | '/events/$eventId/'
    | '/p/$slug/'
    | '/p/$slug/editor/'
    | '/p/$slug/settings/'
    | '/p/$slug/settings/admin-controls/'
    | '/p/$slug/settings/general/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/announcements'
    | '/contacts'
    | '/courses'
    | '/degree-audit-info'
    | '/events'
    | '/mynuspace'
    | '/opportunities'
    | '/sgotinish'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/courses/audit'
    | '/courses/schedule'
    | '/courses/statistics'
    | '/events/$eventId'
    | '/p/$slug'
    | '/p/$slug/editor'
    | '/p/$slug/settings'
    | '/p/$slug/settings/admin-controls'
    | '/p/$slug/settings/general'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/courses'
    | '/_public/'
    | '/_app/account/'
    | '/_app/announcements/'
    | '/_app/contacts/'
    | '/_app/courses/'
    | '/_app/degree-audit-info/'
    | '/_app/events/'
    | '/_app/mynuspace/'
    | '/_app/opportunities/'
    | '/_app/sgotinish/'
    | '/_public/about/'
    | '/_public/privacy-policy/'
    | '/_public/terms-of-service/'
    | '/_app/p/$slug/settings'
    | '/_app/courses/audit/'
    | '/_app/courses/schedule/'
    | '/_app/courses/statistics/'
    | '/_app/events/$eventId/'
    | '/_app/p/$slug/'
    | '/_app/p/$slug/editor/'
    | '/_app/p/$slug/settings/'
    | '/_app/p/$slug/settings/admin-controls/'
    | '/_app/p/$slug/settings/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/announcements/': {
      id: '/_app/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AppAnnouncementsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/degree-audit-info/': {
      id: '/_app/degree-audit-info/'
      path: '/degree-audit-info'
      fullPath: '/degree-audit-info/'
      preLoaderRoute: typeof AppDegreeAuditInfoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mynuspace/': {
      id: '/_app/mynuspace/'
      path: '/mynuspace'
      fullPath: '/mynuspace/'
      preLoaderRoute: typeof AppMynuspaceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/opportunities/': {
      id: '/_app/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sgotinish/': {
      id: '/_app/sgotinish/'
      path: '/sgotinish'
      fullPath: '/sgotinish/'
      preLoaderRoute: typeof AppSgotinishIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PublicPrivacyPolicyIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms-of-service/': {
      id: '/_public/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof PublicTermsOfServiceIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/courses/audit/': {
      id: '/_app/courses/audit/'
      path: '/audit'
      fullPath: '/courses/audit/'
      preLoaderRoute: typeof AppCoursesAuditIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/schedule/': {
      id: '/_app/courses/schedule/'
      path: '/schedule'
      fullPath: '/courses/schedule/'
      preLoaderRoute: typeof AppCoursesScheduleIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/statistics/': {
      id: '/_app/courses/statistics/'
      path: '/statistics'
      fullPath: '/courses/statistics/'
      preLoaderRoute: typeof AppCoursesStatisticsIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/': {
      id: '/_app/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof AppPSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/settings': {
      id: '/_app/p/$slug/settings'
      path: '/p/$slug/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof AppPSlugSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/editor/': {
      id: '/_app/p/$slug/editor/'
      path: '/p/$slug/editor'
      fullPath: '/p/$slug/editor/'
      preLoaderRoute: typeof AppPSlugEditorIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/settings/': {
      id: '/_app/p/$slug/settings/'
      path: '/'
      fullPath: '/p/$slug/settings/'
      preLoaderRoute: typeof AppPSlugSettingsIndexRouteImport
      parentRoute: typeof AppPSlugSettingsRouteRoute
    }
    '/_app/p/$slug/settings/admin-controls/': {
      id: '/_app/p/$slug/settings/admin-controls/'
      path: '/admin-controls'
      fullPath: '/p/$slug/settings/admin-controls/'
      preLoaderRoute: typeof AppPSlugSettingsAdminControlsIndexRouteImport
      parentRoute: typeof AppPSlugSettingsRouteRoute
    }
    '/_app/p/$slug/settings/general/': {
      id: '/_app/p/$slug/settings/general/'
      path: '/general'
      fullPath: '/p/$slug/settings/general/'
      preLoaderRoute: typeof AppPSlugSettingsGeneralIndexRouteImport
      parentRoute: typeof AppPSlugSettingsRouteRoute
    }
  }
}

interface AppCoursesRouteRouteChildren {
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesAuditIndexRoute: typeof AppCoursesAuditIndexRoute
  AppCoursesScheduleIndexRoute: typeof AppCoursesScheduleIndexRoute
  AppCoursesStatisticsIndexRoute: typeof AppCoursesStatisticsIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesAuditIndexRoute: AppCoursesAuditIndexRoute,
  AppCoursesScheduleIndexRoute: AppCoursesScheduleIndexRoute,
  AppCoursesStatisticsIndexRoute: AppCoursesStatisticsIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppPSlugSettingsRouteRouteChildren {
  AppPSlugSettingsIndexRoute: typeof AppPSlugSettingsIndexRoute
  AppPSlugSettingsAdminControlsIndexRoute: typeof AppPSlugSettingsAdminControlsIndexRoute
  AppPSlugSettingsGeneralIndexRoute: typeof AppPSlugSettingsGeneralIndexRoute
}

const AppPSlugSettingsRouteRouteChildren: AppPSlugSettingsRouteRouteChildren = {
  AppPSlugSettingsIndexRoute: AppPSlugSettingsIndexRoute,
  AppPSlugSettingsAdminControlsIndexRoute:
    AppPSlugSettingsAdminControlsIndexRoute,
  AppPSlugSettingsGeneralIndexRoute: AppPSlugSettingsGeneralIndexRoute,
}

const AppPSlugSettingsRouteRouteWithChildren =
  AppPSlugSettingsRouteRoute._addFileChildren(
    AppPSlugSettingsRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAnnouncementsIndexRoute: typeof AppAnnouncementsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDegreeAuditInfoIndexRoute: typeof AppDegreeAuditInfoIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMynuspaceIndexRoute: typeof AppMynuspaceIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
  AppSgotinishIndexRoute: typeof AppSgotinishIndexRoute
  AppPSlugSettingsRouteRoute: typeof AppPSlugSettingsRouteRouteWithChildren
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppPSlugIndexRoute: typeof AppPSlugIndexRoute
  AppPSlugEditorIndexRoute: typeof AppPSlugEditorIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAnnouncementsIndexRoute: AppAnnouncementsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDegreeAuditInfoIndexRoute: AppDegreeAuditInfoIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMynuspaceIndexRoute: AppMynuspaceIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
  AppSgotinishIndexRoute: AppSgotinishIndexRoute,
  AppPSlugSettingsRouteRoute: AppPSlugSettingsRouteRouteWithChildren,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppPSlugIndexRoute: AppPSlugIndexRoute,
  AppPSlugEditorIndexRoute: AppPSlugEditorIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute
  PublicTermsOfServiceIndexRoute: typeof PublicTermsOfServiceIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicTermsOfServiceIndexRoute: PublicTermsOfServiceIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
